apiVersion: apps/v1
kind: Deployment
metadata:
  name: yarah-ms-students
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yarah-ms-students
  template:
    metadata:
      labels:
        app: yarah-ms-students
    spec:
      containers:
      - image: sebasmedina95/yarah-ms-students:latest
        name: yarah-ms-students
        ports:
        - containerPort: 18883
