apiVersion: v1
kind: Service
metadata:
  name: yarah-db-ms-users
spec:
  ports:
    - nodePort: 30002
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: yarah-db-ms-users
  type: NodePort
