apiVersion: apps/v1
kind: Deployment
metadata:
  name: yarah-ms-professors
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yarah-ms-professors
  template:
    metadata:
      labels:
        app: yarah-ms-professors
    spec:
      containers:
      - image: sebasmedina95/yarah-ms-professors:latest
        name: yarah-ms-professors
        ports:
        - containerPort: 18884
