apiVersion: v1
kind: Service
metadata:
  name: yarah-db-ms-students
spec:
  ports:
    - nodePort: 30003
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: yarah-db-ms-students
  type: NodePort
