apiVersion: v1
kind: Service
metadata:
  name: yarah-db-ms-persons
spec:
  ports:
    - nodePort: 30001
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: yarah-db-ms-persons
  type: NodePort
